name: redditoster
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  built_value: ^8.4.3
  built_collection: ^5.0.0
  json_annotation: ^4.7.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  google_fonts: ^3.0.1
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: '>=1.0.0 <3.0.0'
  built_value_generator: ^8.4.3
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true